// web/src/pages/Dashboard.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  Activity,
  CheckCircle,
  XCircle,
  Clock,
  ArrowRight,
} from "lucide-react";
import { listTasks } from "../lib/api";
import type { Task } from "../lib/types";
import { StatusBadge } from "../components/StatusBadge";

export function Dashboard() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    listTasks()
      .then(setTasks)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <p className="text-gray-500">Loading...</p>;
  if (error) return <p className="text-red-600">Error: {error}</p>;

  const running = tasks.filter((t) => t.status === "running").length;
  const completed = tasks.filter((t) => t.status === "completed").length;
  const failed = tasks.filter((t) => t.status === "failed").length;
  const recent = tasks.slice(0, 5);

  const stats = [
    { label: "Total Tasks", value: tasks.length, icon: Activity, color: "text-forge-600" },
    { label: "Running", value: running, icon: Clock, color: "text-blue-600" },
    { label: "Completed", value: completed, icon: CheckCircle, color: "text-green-600" },
    { label: "Failed", value: failed, icon: XCircle, color: "text-red-600" },
  ];

  return (
    <>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">Dashboard</h1>
        <p className="mt-1 text-sm text-gray-500">
          Overview of your ForgeBox instance
        </p>
      </div>

      {/* Stats */}
      <div className="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((s) => (
          <div key={s.label} className="card flex items-center gap-4 p-5">
            <s.icon className={`h-8 w-8 ${s.color}`} />
            <div>
              <p className="text-sm text-gray-500">{s.label}</p>
              <p className="text-2xl font-semibold text-gray-900">{s.value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Recent Tasks */}
      <div className="card mb-8">
        <div className="flex items-center justify-between border-b border-gray-200 px-5 py-4">
          <h2 className="text-lg font-semibold text-gray-900">Recent Tasks</h2>
          <Link to="/tasks" className="btn-primary text-xs">
            Run Task <ArrowRight className="ml-1 h-3 w-3" />
          </Link>
        </div>
        {recent.length === 0 ? (
          <div className="p-8 text-center text-sm text-gray-400">
            No tasks yet.{" "}
            <Link to="/tasks" className="text-forge-600 underline">
              Run a task
            </Link>{" "}
            to get started.
          </div>
        ) : (
          <table className="w-full text-left text-sm">
            <thead className="border-b border-gray-100 text-xs uppercase text-gray-500">
              <tr>
                <th className="px-5 py-3">Status</th>
                <th className="px-5 py-3">Prompt</th>
                <th className="px-5 py-3">Provider</th>
                <th className="px-5 py-3">Cost</th>
                <th className="px-5 py-3">Created</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {recent.map((t) => (
                <tr key={t.id} className="hover:bg-gray-50">
                  <td className="px-5 py-3"><StatusBadge status={t.status} /></td>
                  <td className="max-w-xs truncate px-5 py-3 text-gray-700">
                    {t.prompt.length > 80 ? `${t.prompt.slice(0, 80)}...` : t.prompt}
                  </td>
                  <td className="px-5 py-3 text-gray-600">{t.provider}</td>
                  <td className="px-5 py-3 text-gray-600">${t.cost.toFixed(4)}</td>
                  <td className="px-5 py-3 text-gray-400">
                    {new Date(t.created_at).toLocaleDateString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>

      {/* Quick Actions */}
      <h2 className="mb-4 text-lg font-semibold text-gray-900">Quick Actions</h2>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        {[
          { label: "Run a Task", desc: "Execute an AI task in a secure VM", to: "/tasks" },
          { label: "View Sessions", desc: "Browse active and past sessions", to: "/sessions" },
          { label: "Configure Providers", desc: "Manage LLM provider settings", to: "/settings" },
        ].map((a) => (
          <Link key={a.to} to={a.to} className="card flex items-center justify-between p-5 hover:border-forge-300 transition-colors">
            <div>
              <p className="font-medium text-gray-900">{a.label}</p>
              <p className="text-sm text-gray-500">{a.desc}</p>
            </div>
            <ArrowRight className="h-5 w-5 text-gray-400" />
          </Link>
        ))}
      </div>
    </>
  );
}

// web/src/routes/(admin)/dashboard/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { listTasks } from '$lib/api/client';
	import type { Task } from '$lib/api/types';
	import StatusBadge from '$lib/components/StatusBadge.svelte';

	let tasks = $state<Task[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);

	onMount(async () => {
		try {
			tasks = await listTasks();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load';
		} finally {
			loading = false;
		}
	});

	const running = $derived(tasks.filter((t) => t.status === 'running').length);
	const completed = $derived(tasks.filter((t) => t.status === 'completed').length);
	const failed = $derived(tasks.filter((t) => t.status === 'failed').length);
	const recent = $derived(tasks.slice(0, 5));

	const stats = $derived([
		{ label: 'Total Tasks', value: tasks.length, color: 'primary' },
		{ label: 'Running', value: running, color: 'info' },
		{ label: 'Completed', value: completed, color: 'success' },
		{ label: 'Failed', value: failed, color: 'error' }
	]);
</script>

<div class="page">
	<div class="page__header">
		<h1>Dashboard</h1>
		<p>Overview of your ForgeBox instance</p>
	</div>

	{#if loading}
		<p class="page__loading">Loading...</p>
	{:else if error}
		<p class="page__error">Error: {error}</p>
	{:else}
		<div class="stats">
			{#each stats as stat}
				<div class="stat stat--{stat.color}">
					<p class="stat__label">{stat.label}</p>
					<p class="stat__value">{stat.value}</p>
				</div>
			{/each}
		</div>

		<div class="recent">
			<div class="recent__header">
				<h2>Recent Tasks</h2>
				<a href="/tasks/new" class="btn-primary">Run Task</a>
			</div>

			{#if recent.length === 0}
				<div class="recent__empty">
					No tasks yet. <a href="/tasks/new">Run a task</a> to get started.
				</div>
			{:else}
				<table class="table">
					<thead>
						<tr>
							<th>Status</th>
							<th>Prompt</th>
							<th>Provider</th>
							<th>Cost</th>
							<th>Created</th>
						</tr>
					</thead>
					<tbody>
						{#each recent as task}
							<tr>
								<td><StatusBadge status={task.status} /></td>
								<td class="table__truncate">
									{task.prompt.length > 80 ? `${task.prompt.slice(0, 80)}...` : task.prompt}
								</td>
								<td>{task.provider}</td>
								<td>${task.cost.toFixed(4)}</td>
								<td class="table__muted">{new Date(task.created_at).toLocaleDateString()}</td>
							</tr>
						{/each}
					</tbody>
				</table>
			{/if}
		</div>

		<h2 class="section-title">Quick Actions</h2>
		<div class="actions">
			{#each [
				{ label: 'Run a Task', desc: 'Execute an AI task in a secure VM', href: '/tasks/new' },
				{ label: 'View Tasks', desc: 'Browse active and past tasks', href: '/tasks' },
				{ label: 'Configure Providers', desc: 'Manage LLM provider settings', href: '/providers' }
			] as action}
				<a href={action.href} class="action-card">
					<div>
						<p class="action-card__title">{action.label}</p>
						<p class="action-card__desc">{action.desc}</p>
					</div>
					<span class="action-card__arrow">→</span>
				</a>
			{/each}
		</div>
	{/if}
</div>

<style lang="scss">
	.page {
		&__header {
			margin-bottom: $space-8;

			h1 { font-size: $text-2xl; font-weight: $font-bold; color: $neutral-900; }
			p { margin-top: $space-1; font-size: $text-sm; color: $neutral-500; }
		}

		&__loading { color: $neutral-500; }
		&__error { color: $error-600; }
	}

	.stats {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
		gap: $space-4;
		margin-bottom: $space-8;
	}

	.stat {
		@include card;
		padding: $space-5;

		&__label { font-size: $text-sm; color: $neutral-500; }
		&__value { font-size: $text-2xl; font-weight: $font-semibold; color: $neutral-900; margin-top: $space-1; }

		&--primary { border-left: 3px solid $primary-500; }
		&--info { border-left: 3px solid $info-500; }
		&--success { border-left: 3px solid $success-500; }
		&--error { border-left: 3px solid $error-500; }
	}

	.recent {
		@include card;
		margin-bottom: $space-8;

		&__header {
			@include flex-between;
			padding: $space-4 $space-5;
			border-bottom: 1px solid $neutral-200;
		}

		&__empty {
			padding: $space-8;
			text-align: center;
			font-size: $text-sm;
			color: $neutral-400;

			a { color: $primary-600; text-decoration: underline; }
		}
	}

	.table {
		text-align: left;
		font-size: $text-sm;

		thead { border-bottom: 1px solid $neutral-100; }

		th {
			padding: $space-3 $space-5;
			font-size: $text-xs;
			font-weight: $font-medium;
			text-transform: uppercase;
			color: $neutral-500;
		}

		td { padding: $space-3 $space-5; }

		tbody tr:hover { background: $neutral-50; }
		tbody tr + tr { border-top: 1px solid $neutral-100; }

		&__truncate { max-width: 300px; @include truncate; color: $neutral-700; }
		&__muted { color: $neutral-400; }
	}

	.section-title { margin-bottom: $space-4; }

	.actions {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
		gap: $space-4;
	}

	.action-card {
		@include card;
		@include flex-between;
		padding: $space-5;
		transition: border-color $transition-fast;

		&:hover { border-color: $primary-300; }

		&__title { font-weight: $font-medium; color: $neutral-900; }
		&__desc { font-size: $text-sm; color: $neutral-500; }
		&__arrow { color: $neutral-400; font-size: $text-xl; }
	}
</style>
