// web/src/pages/Settings.tsx
import { useEffect, useState } from "react";
import { clsx } from "clsx";
import { Plug, Radio, Sliders, Plus, CheckCircle, XCircle } from "lucide-react";
import { listProviders } from "../lib/api";
import type { Provider } from "../lib/types";

type Tab = "providers" | "channels" | "general";

const tabs: { key: Tab; label: string; icon: typeof Plug }[] = [
  { key: "providers", label: "Providers", icon: Plug },
  { key: "channels", label: "Channels", icon: Radio },
  { key: "general", label: "General", icon: Sliders },
];

const defaultChannels = [
  { name: "Slack", configured: false },
  { name: "Discord", configured: false },
  { name: "Webhook", configured: true },
  { name: "Email", configured: false },
];

export function Settings() {
  const [activeTab, setActiveTab] = useState<Tab>("providers");
  const [providers, setProviders] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    listProviders()
      .then(setProviders)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  return (
    <>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">Settings</h1>
      </div>

      {/* Tabs */}
      <div className="mb-6 flex gap-1 rounded-lg bg-gray-100 p-1">
        {tabs.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setActiveTab(tab.key)}
            className={clsx(
              "flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors",
              activeTab === tab.key
                ? "bg-white text-gray-900 shadow-sm"
                : "text-gray-500 hover:text-gray-700",
            )}
          >
            <tab.icon className="h-4 w-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {loading && <p className="text-gray-500">Loading...</p>}
      {error && <p className="text-red-600">Error: {error}</p>}

      {/* Providers */}
      {!loading && !error && activeTab === "providers" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-gray-900">Configured Providers</h2>
            <button className="btn-secondary text-xs">
              <Plus className="mr-1 h-3 w-3" /> Add Provider
            </button>
          </div>
          {providers.length === 0 ? (
            <p className="text-sm text-gray-400">No providers configured.</p>
          ) : (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              {providers.map((p) => (
                <div key={p.name} className="card flex items-center justify-between p-5">
                  <div>
                    <p className="font-medium text-gray-900">{p.name}</p>
                    <p className="text-xs text-gray-500">v{p.version} {p.builtin ? "(built-in)" : ""}</p>
                  </div>
                  <span className="badge gap-1 bg-green-100 text-green-700">
                    <CheckCircle className="h-3 w-3" /> Active
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Channels */}
      {!loading && !error && activeTab === "channels" && (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-gray-900">Input Channels</h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {defaultChannels.map((ch) => (
              <div key={ch.name} className="card flex items-center justify-between p-5">
                <div>
                  <p className="font-medium text-gray-900">{ch.name}</p>
                  <p className="text-xs text-gray-500">{ch.configured ? "Configured" : "Not configured"}</p>
                </div>
                {ch.configured ? (
                  <span className="badge gap-1 bg-green-100 text-green-700">
                    <CheckCircle className="h-3 w-3" /> Active
                  </span>
                ) : (
                  <span className="badge gap-1 bg-gray-100 text-gray-500">
                    <XCircle className="h-3 w-3" /> Inactive
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* General */}
      {!loading && !error && activeTab === "general" && (
        <div className="space-y-6">
          <div>
            <h2 className="mb-4 text-lg font-semibold text-gray-900">VM Defaults</h2>
            <div className="card divide-y divide-gray-100">
              {[
                { label: "Memory", value: "512 MB" },
                { label: "vCPUs", value: "1" },
                { label: "Timeout", value: "5 minutes" },
                { label: "Network Access", value: "Disabled" },
              ].map((item) => (
                <div key={item.label} className="flex items-center justify-between px-5 py-3 text-sm">
                  <span className="text-gray-600">{item.label}</span>
                  <span className="font-medium text-gray-900">{item.value}</span>
                </div>
              ))}
            </div>
          </div>
          <div>
            <h2 className="mb-4 text-lg font-semibold text-gray-900">Storage</h2>
            <div className="card px-5 py-4 text-sm text-gray-600">
              Local filesystem storage is active. Configure S3 or GCS backends in the
              ForgeBox configuration file.
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// web/src/routes/(app)/settings/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/state';
	import { listProviders } from '$lib/api/client';
	import type { Provider } from '$lib/api/types';
	import { isTauri } from '$lib/platform';
	import EmptyState from '$lib/components/EmptyState.svelte';
	import AuditLog from '$lib/components/AuditLog.svelte';
	import Team from '$lib/components/Team.svelte';
	import Channels from '$lib/components/Channels.svelte';

	type TabKey = 'general' | 'team' | 'channels' | 'providers' | 'vm' | 'observability' | 'token-usage' | 'audit' | 'connection';
	const validTabs: TabKey[] = ['general', 'team', 'channels', 'providers', 'vm', 'observability', 'token-usage', 'audit', 'connection'];

	function tabFromQuery(value: string | null): TabKey {
		return validTabs.includes(value as TabKey) ? (value as TabKey) : 'general';
	}

	let activeTab = $state<TabKey>(tabFromQuery(page.url.searchParams.get('tab')));



	const vmDefaults = [
		{ label: 'Memory', value: '512 MB' },
		{ label: 'vCPUs', value: '1' },
		{ label: 'Timeout', value: '5 minutes' },
		{ label: 'Network Access', value: 'Disabled' }
	];
	let providers = $state<Provider[]>([]);
	let loading = $state(true);
	let backendUrl = $state('');
	let showTauriSettings = $state(false);

	onMount(async () => {
		showTauriSettings = isTauri();
		if (showTauriSettings) {
			backendUrl = localStorage.getItem('forgebox_api_url') || 'http://localhost:8420/api/v1';
		}
		try {
			providers = await listProviders();
		} catch {
			// ignore
		} finally {
			loading = false;
		}
	});

	function saveBackendUrl() {
		localStorage.setItem('forgebox_api_url', backendUrl);
	}

	const tabs = $derived([
		{ key: 'general' as const, label: 'General' },
		{ key: 'team' as const, label: 'Team' },
		{ key: 'channels' as const, label: 'Channels' },
		{ key: 'providers' as const, label: 'Providers' },
		{ key: 'vm' as const, label: 'VM' },
		{ key: 'observability' as const, label: 'Observability' },
		{ key: 'token-usage' as const, label: 'Token Usage' },
		{ key: 'audit' as const, label: 'Audit Log' },
		...(showTauriSettings ? [{ key: 'connection' as const, label: 'Connection' }] : [])
	]);

	function selectTab(key: TabKey) {
		activeTab = key;
		const url = new URL(window.location.href);
		if (key === 'general') {
			url.searchParams.delete('tab');
		} else {
			url.searchParams.set('tab', key);
		}
		window.history.replaceState(null, '', url);
	}
</script>

<div class="page">
	<div class="page__header">
		<h1>Settings</h1>
	</div>

	<div class="tabs">
		{#each tabs as tab}
			<button
				class="tabs__tab"
				class:tabs__tab--active={activeTab === tab.key}
				onclick={() => selectTab(tab.key)}
			>
				{tab.label}
			</button>
		{/each}
	</div>

	{#if activeTab === 'general'}
		<div class="section">
			<h2>Preferences</h2>
			<p class="section__hint">Display, theme, and notification defaults.</p>
			<div class="settings-card">
				<div class="settings-row">
					<span class="settings-row__label">Theme</span>
					<span class="settings-row__value">System default</span>
				</div>
				<div class="settings-row">
					<span class="settings-row__label">Notifications</span>
					<span class="settings-row__value">Enabled</span>
				</div>
			</div>
		</div>
	{:else if activeTab === 'team'}
		<Team />
	{:else if activeTab === 'channels'}
		<Channels />
	{:else if activeTab === 'providers'}
		<div class="section">
			<h2>Providers</h2>
			<p class="section__hint">LLM backends available to agents and tasks.</p>
			<div class="toolbar">
				<a href="/providers/new" class="btn-primary">Add Provider</a>
			</div>
			{#if loading}
				<p class="text-muted">Loading...</p>
			{:else if providers.length === 0}
				<EmptyState
					title="No providers configured"
					description="Add at least one provider so agents have an LLM to call."
				/>
			{:else}
				<div class="provider-grid">
					{#each providers as p}
						<div class="provider-item">
							<p class="provider-item__name">{p.name}</p>
							<p class="provider-item__meta">v{p.version} {p.builtin ? '(built-in)' : ''}</p>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	{:else if activeTab === 'vm'}
		<div class="section">
			<h2>VM Defaults</h2>
			<p class="section__hint">Firecracker VM defaults, network policies, and resource limits</p>
			<div class="settings-card">
				{#each vmDefaults as item}
					<div class="settings-row">
						<span class="settings-row__label">{item.label}</span>
						<span class="settings-row__value">{item.value}</span>
					</div>
				{/each}
			</div>
		</div>

		<div class="section">
			<h2>Storage</h2>
			<div class="settings-card">
				<div class="settings-info">
					Local filesystem storage is active. Configure S3 or GCS backends in the
					ForgeBox configuration file.
				</div>
			</div>
		</div>
	{:else if activeTab === 'observability'}
		<div class="section">
			<h2>Observability</h2>
			<p class="section__hint">Logs, task execution traces, and error rates</p>
			<EmptyState
				title="No trace data"
				description="Execution traces and logs will appear here once the observability pipeline is connected."
			/>
		</div>
	{:else if activeTab === 'token-usage'}
		<div class="section">
			<h2>Token Usage</h2>
			<p class="section__hint">Usage statistics per user, team, and provider</p>
			<EmptyState
				title="No usage data"
				description="Token usage tracking will appear here once tasks have been run."
			/>
		</div>
	{:else if activeTab === 'audit'}
		<AuditLog />
	{:else if activeTab === 'connection'}
		<div class="section">
			<h2>Backend Connection</h2>
			<p class="section__hint">Override the gateway URL used by this client.</p>
			<div class="settings-card">
				<div class="connection-form">
					<label class="connection-field">
						<span>Backend URL</span>
						<input type="url" bind:value={backendUrl} placeholder="http://localhost:8420/api/v1" />
					</label>
					<button class="btn-primary" onclick={saveBackendUrl}>Save</button>
				</div>
			</div>
		</div>
	{/if}
</div>

<style lang="scss">
	.page {
		&__header {
			margin-bottom: $space-8;

			h1 { font-size: $text-2xl; font-weight: $font-bold; color: $neutral-900; }
		}
	}

	.tabs {
		display: flex;
		gap: $space-1;
		padding: $space-1;
		background: $neutral-100;
		border-radius: $radius-lg;
		margin-bottom: $space-6;

		&__tab {
			@include btn;
			color: $neutral-500;
			background: transparent;

			&--active {
				background: $neutral-0;
				color: $neutral-900;
				box-shadow: $shadow-sm;
			}

			&:hover:not(&--active) { color: $neutral-700; }
		}
	}

	.text-muted { color: $neutral-500; font-size: $text-sm; }

	.toolbar {
		display: flex;
		justify-content: flex-end;
		margin-bottom: $space-4;
	}

	.section {
		h2 { margin-bottom: $space-4; }

		& + & { margin-top: $space-8; }

		&__hint {
			margin: -$space-2 0 $space-4;
			font-size: $text-sm;
			color: $neutral-500;
		}
	}

	.settings-card { @include card; }

	.settings-row {
		@include flex-between;
		padding: $space-3 $space-5;
		font-size: $text-sm;

		& + & { border-top: 1px solid $neutral-100; }

		&__label { color: $neutral-600; }
		&__value { font-weight: $font-medium; color: $neutral-900; }
	}

	.provider-grid {
		display: grid;
		grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
		gap: $space-3;
	}

	.provider-item {
		@include card;
		padding: $space-4;

		&__name { font-weight: $font-medium; color: $neutral-900; }
		&__meta { font-size: $text-xs; color: $neutral-500; margin-top: $space-1; }
	}

	.settings-info {
		padding: $space-4 $space-5;
		font-size: $text-sm;
		color: $neutral-600;
	}

	.connection-form {
		padding: $space-5;
		display: flex;
		align-items: flex-end;
		gap: $space-3;
	}

	.connection-field {
		flex: 1;
		display: flex;
		flex-direction: column;
		gap: $space-1;

		span { font-size: $text-sm; font-weight: $font-medium; color: $neutral-700; }
		input { @include input-base; }
	}
</style>
