// web/src/lib/components/ProviderBadge.svelte
<script lang="ts">
	interface Props {
		name: string;
	}

	let { name }: Props = $props();

	const colors: Record<string, string> = {
		anthropic: 'badge--amber',
		openai: 'badge--emerald',
		google: 'badge--blue',
		ollama: 'badge--purple',
		bedrock: 'badge--orange',
		vertex: 'badge--cyan',
		openrouter: 'badge--pink'
	};

	const colorClass = $derived(colors[name.toLowerCase()] ?? 'badge--neutral');
</script>

<span class="badge {colorClass}">{name}</span>

<style lang="scss">
	.badge {
		@include badge;

		&--amber { background: #fef3c7; color: #92400e; }
		&--emerald { background: $success-100; color: $success-700; }
		&--blue { background: $info-100; color: $info-600; }
		&--purple { background: #ede9fe; color: #5b21b6; }
		&--orange { background: #ffedd5; color: #9a3412; }
		&--cyan { background: #cffafe; color: #155e75; }
		&--pink { background: #fce7f3; color: #9d174d; }
		&--neutral { background: $neutral-100; color: $neutral-700; }
	}
</style>

// web/src/components/ProviderBadge.tsx
import { clsx } from "clsx";

const providerColors: Record<string, string> = {
  anthropic: "bg-amber-100 text-amber-800",
  openai: "bg-emerald-100 text-emerald-800",
  google: "bg-blue-100 text-blue-800",
  ollama: "bg-purple-100 text-purple-800",
  bedrock: "bg-orange-100 text-orange-800",
  vertex: "bg-cyan-100 text-cyan-800",
  openrouter: "bg-pink-100 text-pink-800",
};

export function ProviderBadge({ name }: { name: string }) {
  const color = providerColors[name.toLowerCase()] ?? "bg-gray-100 text-gray-700";

  return (
    <span className={clsx("badge", color)}>
      {name}
    </span>
  );
}
