// web/src/pages/AuditLog.tsx
import { useEffect, useState } from "react";
import { format } from "date-fns";
import { Shield, Search } from "lucide-react";
import { clsx } from "clsx";
import { listAuditEntries } from "../lib/api";
import type { AuditEntry } from "../lib/types";

export function AuditLog() {
  const [entries, setEntries] = useState<AuditEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Filters
  const [userId, setUserId] = useState("");
  const [decision, setDecision] = useState<"all" | "allow" | "deny">("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  useEffect(() => {
    listAuditEntries()
      .then(setEntries)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  const filtered = entries.filter((e) => {
    if (userId && !e.user_id.toLowerCase().includes(userId.toLowerCase())) return false;
    if (decision !== "all" && e.decision !== decision) return false;
    if (dateFrom && e.timestamp < dateFrom) return false;
    if (dateTo && e.timestamp > dateTo) return false;
    return true;
  });

  return (
    <>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">Audit Log</h1>
        <p className="mt-1 text-sm text-gray-500">
          Track all tool calls and permission decisions.
        </p>
      </div>

      {/* Filters */}
      <div className="mb-6 flex flex-wrap items-end gap-3">
        <div>
          <label className="mb-1 block text-xs font-medium text-gray-600">User ID</label>
          <div className="relative">
            <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-gray-400" />
            <input className="input pl-8 w-48" placeholder="Filter by user..." value={userId} onChange={(e) => setUserId(e.target.value)} />
          </div>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-gray-600">Decision</label>
          <select className="input w-32" value={decision} onChange={(e) => setDecision(e.target.value as "all" | "allow" | "deny")}>
            <option value="all">All</option>
            <option value="allow">Allow</option>
            <option value="deny">Deny</option>
          </select>
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-gray-600">From</label>
          <input className="input w-40" type="text" placeholder="YYYY-MM-DD" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} />
        </div>
        <div>
          <label className="mb-1 block text-xs font-medium text-gray-600">To</label>
          <input className="input w-40" type="text" placeholder="YYYY-MM-DD" value={dateTo} onChange={(e) => setDateTo(e.target.value)} />
        </div>
      </div>

      {loading && <p className="text-gray-500">Loading...</p>}
      {error && <p className="text-red-600">Error: {error}</p>}

      {!loading && !error && filtered.length === 0 && (
        <div className="card flex flex-col items-center justify-center p-12 text-center text-gray-400">
          <Shield className="mb-3 h-10 w-10" />
          <p className="text-sm">No audit entries found.</p>
        </div>
      )}

      {!loading && !error && filtered.length > 0 && (
        <div className="card overflow-hidden">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-gray-100 bg-gray-50 text-xs uppercase text-gray-500">
              <tr>
                <th className="px-5 py-3">Timestamp</th>
                <th className="px-5 py-3">User</th>
                <th className="px-5 py-3">Action</th>
                <th className="px-5 py-3">Tool</th>
                <th className="px-5 py-3">Decision</th>
                <th className="px-5 py-3">Reason</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {filtered.map((entry) => (
                <tr key={entry.id} className="hover:bg-gray-50">
                  <td className="whitespace-nowrap px-5 py-3 text-gray-400">
                    {format(new Date(entry.timestamp), "MMM d, yyyy HH:mm:ss")}
                  </td>
                  <td className="px-5 py-3 font-mono text-xs text-gray-700">
                    {entry.user_id.slice(0, 8)}
                  </td>
                  <td className="px-5 py-3 text-gray-600">{entry.action}</td>
                  <td className="px-5 py-3 font-mono text-xs text-gray-600">{entry.tool ?? "-"}</td>
                  <td className="px-5 py-3">
                    <span className={clsx(
                      "badge",
                      entry.decision === "allow" ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700",
                    )}>
                      {entry.decision}
                    </span>
                  </td>
                  <td className="max-w-xs truncate px-5 py-3 text-gray-500">
                    {entry.reason ?? "-"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}

// web/src/lib/components/AuditLog.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { format } from 'date-fns';
	import { listAuditEntries } from '$lib/api/client';
	import type { AuditEntry } from '$lib/api/types';
	import EmptyState from '$lib/components/EmptyState.svelte';

	let entries = $state<AuditEntry[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);

	let userId = $state('');
	let decision = $state<'all' | 'allow' | 'deny'>('all');
	let dateFrom = $state('');
	let dateTo = $state('');

	const filtered = $derived(
		entries.filter((e) => {
			if (userId && !e.user_id.toLowerCase().includes(userId.toLowerCase())) return false;
			if (decision !== 'all' && e.decision !== decision) return false;
			if (dateFrom && e.timestamp < dateFrom) return false;
			if (dateTo && e.timestamp > dateTo) return false;
			return true;
		})
	);

	onMount(async () => {
		try {
			entries = await listAuditEntries();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to load';
		} finally {
			loading = false;
		}
	});
</script>

<section class="section">
	<h2>Audit Log</h2>
	<p class="section__hint">Track all tool calls and permission decisions</p>
	<div class="filters">
	<label class="filter">
		<span>User ID</span>
		<input type="text" placeholder="Filter by user..." bind:value={userId} />
	</label>
	<label class="filter">
		<span>Decision</span>
		<select bind:value={decision}>
			<option value="all">All</option>
			<option value="allow">Allow</option>
			<option value="deny">Deny</option>
		</select>
	</label>
	<label class="filter">
		<span>From</span>
		<input type="text" placeholder="YYYY-MM-DD" bind:value={dateFrom} />
	</label>
	<label class="filter">
		<span>To</span>
		<input type="text" placeholder="YYYY-MM-DD" bind:value={dateTo} />
	</label>
</div>

{#if loading}
	<p class="text-muted">Loading...</p>
{:else if error}
	<p class="text-error">Error: {error}</p>
{:else if filtered.length === 0}
	<EmptyState
		title="No audit entries found"
		description="Audit entries will appear here when tools are executed."
	/>
{:else}
	<div class="table-wrap">
		<table class="table">
			<thead>
				<tr>
					<th>Timestamp</th>
					<th>User</th>
					<th>Action</th>
					<th>Tool</th>
					<th>Decision</th>
					<th>Reason</th>
				</tr>
			</thead>
			<tbody>
				{#each filtered as entry}
					<tr>
						<td class="table__nowrap table__muted">
							{format(new Date(entry.timestamp), 'MMM d, yyyy HH:mm:ss')}
						</td>
						<td class="table__mono">{entry.user_id.slice(0, 8)}</td>
						<td>{entry.action}</td>
						<td class="table__mono">{entry.tool ?? '-'}</td>
						<td>
							<span class="decision" class:decision--allow={entry.decision === 'allow'} class:decision--deny={entry.decision === 'deny'}>
								{entry.decision}
							</span>
						</td>
						<td class="table__truncate table__muted">{entry.reason ?? '-'}</td>
					</tr>
				{/each}
			</tbody>
		</table>
	</div>
{/if}
</section>

<style lang="scss">
	.section {
		h2 { margin-bottom: $space-4; }

		&__hint {
			margin: -$space-2 0 $space-4;
			font-size: $text-sm;
			color: $neutral-500;
		}
	}

	.text-muted { color: $neutral-500; }
	.text-error { color: $error-600; }

	.filters {
		display: flex;
		flex-wrap: wrap;
		gap: $space-3;
		align-items: flex-end;
		margin-bottom: $space-6;
	}

	.filter {
		display: flex;
		flex-direction: column;
		gap: $space-1;

		span { font-size: $text-xs; font-weight: $font-medium; color: $neutral-600; }
		input, select { @include input-base; width: auto; }
	}

	.table-wrap {
		@include card;
		overflow: hidden;
	}

	.table {
		text-align: left;
		font-size: $text-sm;

		thead {
			background: $neutral-50;
			border-bottom: 1px solid $neutral-100;
		}

		th {
			padding: $space-3 $space-5;
			font-size: $text-xs;
			font-weight: $font-medium;
			text-transform: uppercase;
			color: $neutral-500;
		}

		td { padding: $space-3 $space-5; }

		tbody tr:hover { background: $neutral-50; }
		tbody tr + tr { border-top: 1px solid $neutral-100; }

		&__nowrap { white-space: nowrap; }
		&__mono { font-family: $font-mono; font-size: $text-xs; color: $neutral-700; }
		&__muted { color: $neutral-400; }
		&__truncate { max-width: 200px; @include truncate; }
	}

	.decision {
		@include badge;

		&--allow { background: $success-100; color: $success-700; }
		&--deny { background: $error-100; color: $error-700; }
	}
</style>
