// web/src/components/TaskStream.tsx
import { useEffect, useRef } from "react";
import { clsx } from "clsx";
import { Terminal, Wrench, AlertCircle } from "lucide-react";
import type { TaskEvent } from "../lib/types";

interface TaskStreamProps {
  events: TaskEvent[];
  isRunning: boolean;
}

export function TaskStream({ events, isRunning }: TaskStreamProps) {
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [events.length]);

  if (events.length === 0 && !isRunning) {
    return null;
  }

  return (
    <div className="card overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-2 border-b border-gray-200 bg-gray-50 px-4 py-2">
        <Terminal className="h-4 w-4 text-gray-500" />
        <span className="text-sm font-medium text-gray-700">Output</span>
        {isRunning && (
          <span className="ml-auto flex items-center gap-1 text-xs text-blue-600">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-blue-600" />
            Streaming
          </span>
        )}
      </div>

      {/* Event list */}
      <div className="max-h-[500px] overflow-y-auto bg-gray-900 p-4 font-mono text-sm">
        {events.map((event, i) => (
          <EventLine key={i} event={event} />
        ))}
        {isRunning && (
          <span className="inline-block h-4 w-2 animate-pulse bg-gray-400" />
        )}
        <div ref={bottomRef} />
      </div>
    </div>
  );
}

function EventLine({ event }: { event: TaskEvent }) {
  switch (event.type) {
    case "text_delta":
      return <span className="text-gray-100 whitespace-pre-wrap">{event.text}</span>;

    case "tool_call":
      return (
        <div className="my-2 flex items-start gap-2 rounded border border-gray-700 bg-gray-800 p-2">
          <Wrench className="mt-0.5 h-3.5 w-3.5 shrink-0 text-forge-400" />
          <div>
            <span className="font-semibold text-forge-300">
              {event.tool_call?.name}
            </span>
            <pre className="mt-1 text-xs text-gray-400 overflow-x-auto">
              {event.tool_call?.input}
            </pre>
          </div>
        </div>
      );

    case "tool_result":
      return (
        <div
          className={clsx(
            "my-1 rounded border p-2 text-xs whitespace-pre-wrap",
            event.result?.is_error
              ? "border-red-800 bg-red-950 text-red-300"
              : "border-gray-700 bg-gray-800 text-gray-300",
          )}
        >
          {event.result?.content}
        </div>
      );

    case "error":
      return (
        <div className="my-2 flex items-center gap-2 text-red-400">
          <AlertCircle className="h-4 w-4" />
          <span>{event.error}</span>
        </div>
      );

    case "done":
      return (
        <div className="mt-3 border-t border-gray-700 pt-2 text-xs text-gray-500">
          Task completed
        </div>
      );

    default:
      return null;
  }
}

// web/src/lib/components/TaskStream.svelte
<script lang="ts">
	import type { TaskEvent } from '$lib/api/types';

	interface Props {
		events: TaskEvent[];
		isRunning: boolean;
	}

	let { events, isRunning }: Props = $props();
	let container: HTMLDivElement | undefined = $state();

	$effect(() => {
		// Scroll to bottom on new events
		if (events.length && container) {
			container.scrollTop = container.scrollHeight;
		}
	});
</script>

{#if events.length > 0 || isRunning}
	<div class="stream">
		<div class="stream__header">
			<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
				<polyline points="4 17 10 11 4 5" /><line x1="12" y1="19" x2="20" y2="19" />
			</svg>
			<span>Output</span>
			{#if isRunning}
				<span class="stream__live">
					<span class="stream__pulse"></span>
					Streaming
				</span>
			{/if}
		</div>

		<div class="stream__body" bind:this={container}>
			{#each events as event}
				{#if event.type === 'text_delta'}
					<span class="stream__text">{event.text}</span>
				{:else if event.type === 'tool_call'}
					<div class="stream__tool">
						<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
							<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z" />
						</svg>
						<div>
							<span class="stream__tool-name">{event.tool_call?.name}</span>
							<pre class="stream__tool-input">{event.tool_call?.input}</pre>
						</div>
					</div>
				{:else if event.type === 'tool_result'}
					<div class="stream__result" class:stream__result--error={event.result?.is_error}>
						{event.result?.content}
					</div>
				{:else if event.type === 'error'}
					<div class="stream__error">
						<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
							<circle cx="12" cy="12" r="10" /><line x1="12" y1="8" x2="12" y2="12" /><line x1="12" y1="16" x2="12.01" y2="16" />
						</svg>
						{event.error}
					</div>
				{:else if event.type === 'done'}
					<div class="stream__done">Task completed</div>
				{/if}
			{/each}
			{#if isRunning}
				<span class="stream__cursor"></span>
			{/if}
		</div>
	</div>
{/if}

<style lang="scss">
	.stream {
		@include card;
		overflow: hidden;

		&__header {
			@include flex-between;
			padding: $space-2 $space-4;
			border-bottom: 1px solid $neutral-200;
			background: $neutral-50;
			font-size: $text-sm;
			font-weight: $font-medium;
			color: $neutral-700;

			display: flex;
			align-items: center;
			gap: $space-2;
		}

		&__live {
			margin-left: auto;
			display: flex;
			align-items: center;
			gap: $space-1;
			font-size: $text-xs;
			color: $info-600;
		}

		&__pulse {
			width: 6px;
			height: 6px;
			border-radius: 50%;
			background: $info-600;
			animation: pulse 1.5s ease-in-out infinite;
		}

		&__body {
			max-height: 500px;
			overflow-y: auto;
			@include scrollbar-thin;
			background: $neutral-900;
			padding: $space-4;
			font-family: $font-mono;
			font-size: $text-sm;
		}

		&__text {
			color: $neutral-100;
			white-space: pre-wrap;
		}

		&__tool {
			display: flex;
			align-items: flex-start;
			gap: $space-2;
			margin: $space-2 0;
			padding: $space-2;
			border: 1px solid $neutral-700;
			border-radius: $radius-md;
			background: $neutral-800;
			color: $primary-300;
		}

		&__tool-name {
			font-weight: $font-semibold;
			color: $primary-300;
		}

		&__tool-input {
			margin-top: $space-1;
			font-size: $text-xs;
			color: $neutral-400;
			overflow-x: auto;
		}

		&__result {
			margin: $space-1 0;
			padding: $space-2;
			border: 1px solid $neutral-700;
			border-radius: $radius-md;
			background: $neutral-800;
			color: $neutral-300;
			font-size: $text-xs;
			white-space: pre-wrap;

			&--error {
				border-color: $error-700;
				background: rgba($error-600, 0.15);
				color: $error-500;
			}
		}

		&__error {
			display: flex;
			align-items: center;
			gap: $space-2;
			margin: $space-2 0;
			color: $error-500;
		}

		&__done {
			margin-top: $space-3;
			padding-top: $space-2;
			border-top: 1px solid $neutral-700;
			font-size: $text-xs;
			color: $neutral-500;
		}

		&__cursor {
			display: inline-block;
			width: 8px;
			height: 16px;
			background: $neutral-400;
			animation: pulse 1s ease-in-out infinite;
		}
	}

	@keyframes pulse {
		0%, 100% { opacity: 1; }
		50% { opacity: 0.4; }
	}
</style>
